commerce/commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf import settings
from django.conf.urls.static import static

# amazon s3 photo storage needs to be added to the project
# now we can add the following to the settings.py file: static files

urlpatterns = [
    path('', include('core.urls')),
    path('products/', include('product.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:product_pk>/', views.new_conversation, name='new'),
]

commerce/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm
# auth_views is a module that contains all the views for authentication
# we are importing the LoginView class from the module


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    # need log out
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

commerce/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

commerce/product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.products, name='products'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),


]

commerce/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    # override the default fields
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'your username',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'your password',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))


class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'your username',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'your email address',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'your password',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'confirm your password',
        'class': 'w-full py-4 px-6 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500'
        }))
    

commerce/core/views.py
from django.shortcuts import render, redirect
# import models from product app, not from core app
from product.models import Product, Category
from .forms import SignupForm

# Create your views here.
def index(request):
    products = Product.objects.filter(is_sold=False)[0:6] # get first 6 products
    categories = Category.objects.all()
    return render(request, 'core/index.html', { 
        'categories': categories,
        'products': products
        })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
    else:     
        form = SignupForm()
    return render(request, 'core/signup.html', {
        'form': form
        })

commerce/core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Commerce</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Commerce</a>

            <div class="space-x-6">
                <a href="{% url 'product:products' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                <a href="{% url 'product:new' %}" class="text-lg font-semibold hover:text-gray-500">New product</a>

                    {% if request.user.is_authenticated %}
                        
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out</a>
                    
                    {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                    {% endif %}    
            </div>
        </nav>


</div>
        <div class="px-6 py-6 ">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla bla.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

commerce/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}


{% block content %}
    
    <h1>The CONTACT page</h1>
    <p>Some content</p>
{% endblock %}

commerce/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest products</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for product in products %}
                <div>
                    <a href="{% url 'product:detail' product.id %}">
                        <div>
                            <img src="{{ product.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ product.name }}</h2>
                            <p class="text-gray-500">Price: {{ product.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
<!-- SPLIT here -->
   
    <!-- Split -->
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.products.count }} products</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

commerce/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 bg-gray-100 rounded-xl ">
    <h1 class="text-center mb-6 text-3xl">Log in</h1>
    <form action="." method="POST" class="px-3 py-3">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        {{ form.non_field_errors}}
        
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Username</label>
            {{ form.username }}
        </div>
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Email</label>
            {{ form.email }}
        </div>
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Password</label>
            {{ form.password }}
        </div>
       

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>

        {% endif %}
        <button type="submit" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log in</button>
    </form>
</div>
{% endblock %}

commerce/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 bg-gray-100 rounded-xl ">
    <h1 class="text-center mb-6 text-3xl">Sign up</h1>
    <form action="." method="POST" class="px-3 py-3">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        {{ form.non_field_errors}}
        
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Username</label>
            {{ form.username }}
        </div>
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Email</label>
            {{ form.email }}
        </div>
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Password</label>
            {{ form.password1 }}
        </div>
        <div class="mb-3 flex flex-col">
            <label for="" class="mb-2">Repeat Password</label>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>

        {% endif %}
        <button type="submit" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</button>
    </form>
</div>
{% endblock %}